---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # pre_tasks:
  #   - name: "wait 600 seconds for target connection to become reachable/usable."
  #     ansible.builtin.wait_for_connection:
  #       timeout: 600

  # - name: "install python for Ansible."
  #   become: true
  #   command: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
  #   changed_when: false

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity{.ts,.js}
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    - TYPEORM_MIGRATIONS: ./migrations/.*ts
    - TYPEORM_MIGRATIONS_DIR: ./migrations
    - NODE_ENV: production 
    - VERSION: "1"

  roles:
    - deploy