---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install node dependencies"
  shell: |
    cd ~/backend-app
    npm install

- name: "Run node using pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start npm -- start
    #pm2 start main.js

- name:
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
